### PR TITLE
Set AccessControl.Entry and AccessControl.Level public

### PR DESCRIPTION
**Pull request by Steven-Chan**
I cannot define an ACL since these two classes are package protected.

### CODE REVIEW

**Comment by Steven-Chan** [comment]
I found this "problem" when writing guides, but seems thing does not work like that in Android SDK. ACL methods are called directly to the records.

**Comment by Steven-Chan** [comment]
Oh, this will make setting default acl not working.

**Comment by rickmak** [comment]
So.... May @Steven-Chan update the PR.

**Comment by ben181231** [comment]
Any update for this ?

**Comment by Steven-Chan** [comment]
Sorry, my comment was a bit confusing.

I meant this PR is required to allow developers to construct an ACL object to set default ACL.

**Comment by rickmak** [comment]
Merge via 948a359

**Pull request closed without merging**
