### PR TITLE
Add support for Android SDK version 26.

### PR DESCRIPTION
**Pull request by mhdsmr2**
Fixes issue #158.

### CODE REVIEW

**Comment by mhdsmr2** [comment]
The configuration of Travis CI must be changed. The _build-tools_ and _android_ version must be updated for a successful build.

**Comment by mhdsmr2** [comment]
@HenryHins, Can you please merge this.

**Comment by chpapa** [comment]
I have assigned to @rickmak to help.

**Comment by mhdsmr2** [comment]
Thank you :)

**Comment by mhdsmr2** [comment]
@rickmak Tell me if there's something else I have to do.

**Comment by rickmak** [comment]
I updated the Travis configuration and merged to master. Thank your contribution.

**Comment by mhdsmr2** [comment]
Thanks for the merge.

**Pull request merged**
