### PR TITLE
Move skygear to skygear_core module, include it in skygear's build

### PR DESCRIPTION
**Pull request by b123400**
connect https://github.com/SkygearIO/skygear-SDK-Android/issues/123

### CODE REVIEW

**Comment by cheungpat** [comment]
requesting review @ben181231

**Comment by cheungpat** [comment]
@b123400 I have reverted the merge because the scaffolding android project cannot install skygear anymore.

```
$ ./gradlew -q build
Using build tools version: 25.0.3
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find io.skygear:skygear_core:0.24.0.
     Required by:
         project :app > io.skygear:skygear:0.24.0
```

**Comment by b123400** [comment]
Oh no, that's strange. But we will have another module separation anyway...

**Comment by cheungpat** [comment]
> Oh no, that's strange. But we will have another module separation anyway...

Yea! Exciting isn’t it?

**Pull request merged**
