### PR TITLE
Dependency Update

### PR DESCRIPTION
**Pull request by seventhmoon**
TargetSdk is now 25
Google Play Services is now v10.2.0
Updated .travis.yml for using Sdk 25
Added lintOptions - abortOnError changed to false as to force build

### CODE REVIEW

**Comment by ben181231** [comment]
This PR includes #95 ?

**Comment by seventhmoon** [comment]
Yes. This PR includes #95. 
I also include the changes in .travis.yml so this PR could build.

(forget about #95 please)

**Comment by cheungpat** [comment]
um... would be great if @seventhmoon can clean up the commit history when this PR is ready to merge.

**Comment by seventhmoon** [comment]
Sorry, I am still a newbie on making PR.

**Comment by cheungpat** [comment]
> Sorry, I am still a newbie on making PR.

That’s okay! We all are newbies once.

**Comment by seventhmoon** [comment]
WuuuuArrrrr...
Sorry, did something wrong when doing "git rebase -i HEAD" ...

**Pull request closed without merging**
