### PR TITLE
Make pubsub trust all certs

### PR DESCRIPTION
**Pull request by ben181231**
connect #62

ref. https://github.com/TooTallNate/Java-WebSocket#wss-support
ref. https://github.com/TooTallNate/Java-WebSocket/issues/141#issuecomment-149303289

### CODE REVIEW

**Comment by cheungpat** [comment]
Trusting all certificates including invalid ones?

**Comment by ben181231** [comment]
@rickmak @cheungpat Do you think we should change the web socket library ?

**Comment by rickmak** [comment]
It is not acceptable to trusting all certificates unconditionally.

Tried `KeyStore.getInstance("AndroidCAStore")`?

**Comment by ben181231** [comment]
Okay. Let me find some ways to make it work.

**Pull request closed without merging**
